import React, { useEffect, useState } from 'react'
import d from 'next/dynamic'
import Head from 'next/head'

// Librerias de Terceros
import { useDisclosure } from '@chakra-ui/hooks'

// Componentes
import Header from '@/components/Header'
import MobileNav from '@/components/MobileNav'

// Importaciones dinamicas
const Sidebar = d(() => import('@/components/Sidebar'))
const SearchModal = d(() => import('@/components/SearchModal'))
const Landing = d(() => import('@/sections/Landing'), { ssr: false })

const Home = () => {
  const modal = useDisclosure()
  const sidebar = useDisclosure()
  const [loadChunk, setLoadChunk] = useState(false)

  useEffect(() => {
    if (modal.isOpen || sidebar.isOpen) setLoadChunk(true)
  }, [modal.isOpen, sidebar.isOpen])

  return (
    <>
      <Head>
        <title>Elitario</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* FIRTS LOAD */}
      <Header />
      <MobileNav {...{ modal, sidebar }} />
      <Landing />

      {/* LOAD LATER */}
      {loadChunk ? <Sidebar {...sidebar} /> : null}
      {loadChunk ? <SearchModal {...modal} /> : null}
    </>
  )
}

export default Home
