import React, { useState } from 'react'
import Head from 'next/head'

// Terceros
import { Icon } from '@chakra-ui/icon'
import {
  Box,
  Flex,
  Text,
  Stack,
  Heading,
  Container,
  SimpleGrid
} from '@chakra-ui/layout'
import { useDisclosure } from '@chakra-ui/react'

// components
import Footer from '@/components/Footer'
import Header from '@/sections/Pago/Header'
import { Button } from '@/components/Button'
import VirtualCup from '@/components/VirtualCup'
import PaymentStepper from '@/components/PaymentStepper'
import ProductList from '@/components/CardProduct/ProductList'

// Icons
import { CupIcon } from '@/assets/icons'

const pago = () => {
  const [canBuy, setCanBuy] = useState(false)

  return (
    <Box
      bgSize="contain"
      bgRepeat="repeat"
      bgPosition="center"
      bgImage="url(/images/heroPattern.webp)"
    >
      <Head>
        <title>Elitario | Pago</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <Container
        w="90%"
        maxW="1200px"
        pt={{
          base: 10,
          md: 20,
          lg: 28
        }}
        pb={{ base: 16, md: 24, lg: 36 }}
      >
        <SimpleGrid
          templateColumns={{
            base: 'minmax(0, 1fr)',
            md: '1fr minmax(0, 350px)'
          }}
        >
          <PaymentStepper valid={setCanBuy} />

          <Box
            px={4}
            py={5}
            w="full"
            mx="auto"
            maxW="350px"
            rounded="sm"
            h="fit-content"
            bg="surfaceCards.800"
            mt={{ base: 10, md: 0 }}
          >
            <Text as="h3" mb={5} color="white" fontSize="lg">
              RESUMEN DE TU PEDIDO
            </Text>
            <Flex mb={{ base: 3 }} justify="space-between">
              <Text color="surfaceCards.200">Productos (2)</Text>
              <Text color="surfaceCards.200">s/ 240.00</Text>
            </Flex>

            {/* Lista de Productos */}
            <Stack mb={{ base: 3 }} w="full" mx="auto">
              <ProductList />
              <ProductList />
            </Stack>

            <Flex mb={{ base: 3 }} justify="space-between">
              <Flex align="center">
                <Text color="surfaceCards.200" mr={2}>
                  Copas Virtuales
                </Text>
                <VirtualCup />
              </Flex>
              <Text color="surfaceCards.200">
                +20 <Icon as={CupIcon} fill="primary.500" />
              </Text>
            </Flex>

            <Flex justify="space-between">
              <Text color="surfaceCards.200">Costo de envío</Text>
              <Text color="surfaceCards.200">Por confirmar</Text>
            </Flex>

            <Flex my={5} justify="space-between">
              <Text color="white" fontSize={{ base: 'lg' }} fontWeight="500">
                TOTAL
              </Text>
              <Text color="white" fontSize={{ base: 'lg' }} fontWeight="500">
                s/ 240.00
              </Text>
            </Flex>

            <Button disabled={!canBuy} w="full">
              FINALIZAR COMPRA
            </Button>
          </Box>
        </SimpleGrid>
      </Container>

      <Footer />
    </Box>
  )
}

export default pago
