import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

// Terceros
import { Icon } from '@chakra-ui/icon'
import { Image } from '@chakra-ui/image'
import { Button as ButtonC, IconButton } from '@chakra-ui/button'
import {
  Flex,
  Container,
  Heading,
  Text,
  Box,
  Stack,
  SimpleGrid
} from '@chakra-ui/layout'
import { useDisclosure } from '@chakra-ui/react'

// components
import Footer from '@/components/Footer'
import { Button } from '@/components/Button'
import AuthModal from '@/components/AuthModal'
import VirtualCup from '@/components/VirtualCup'
import ProductList from '@/components/CardProduct/ProductList'

// Icons
import { CupIcon, PhoneIcon } from '@/assets/icons'

const pago = () => {
  const { isOpen, onOpen, onClose } = useDisclosure()

  return (
    <Box
      bgSize="contain"
      bgRepeat="repeat"
      bgPosition="center"
      bgImage="url(/images/heroPattern.webp)"
    >
      <Head>
        <title>Elitario | Pago</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <AuthModal {...{ isOpen, onClose }} />

      <Box py={4} px={2} as="nav" bg="negro.900">
        <Flex
          w="90%"
          mx="auto"
          maxW="1150px"
          pos="relative"
          align="center"
          justify={{ base: 'center', md: 'space-between' }}
        >
          <Link href="/">
            <a>
              <Image w={100} objectFit="contain" src="/logo/index.svg" />
            </a>
          </Link>
          <ButtonC
            variant="ghost"
            colorScheme="primary"
            display={{ base: 'none', md: 'flex' }}
            leftIcon={<Icon as={PhoneIcon} fill="primary.500" />}
          >
            AYUDA PERSONALIZADA
          </ButtonC>
          <IconButton
            isRound
            right={5}
            pos="absolute"
            variant="ghost"
            colorScheme="primary"
            display={{ base: 'flex', md: 'none' }}
            icon={<Icon as={PhoneIcon} fill="primary.500" />}
          />
        </Flex>
      </Box>

      <Container
        w="90%"
        maxW="1200px"
        pt={{ base: 10, md: 20, lg: 28 }}
        pb={{ base: 16, md: 24, lg: 36 }}
      >
        <SimpleGrid
          templateColumns={{
            base: 'minmax(0, 1fr)',
            md: '1fr minmax(0, 350px)'
          }}
        >
          <Box mr={{ sm: 5 }}>
            <Heading
              mb={3}
              color="white"
              fontWeight="500"
              fontSize={{ base: 'xl', md: '3xl' }}
            >
              Bienvenido a ELITARIO.COM
            </Heading>
            <Text
              mb={3}
              color="surfaceCards.200"
              fontSize={{ base: 'sm', md: 'lg' }}
            >
              Para continuar con tu compra, ingresa tu e-mail o inicia sesión
              con Facebook.
            </Text>

            <Button onClick={onOpen} w={{ base: 'full', sm: 'fit-content' }}>
              INICIAR SESIÓN / CREAR NUEVA CUENTA
            </Button>
          </Box>

          <Box
            px={4}
            py={5}
            w="full"
            mx="auto"
            maxW="350px"
            rounded="sm"
            h="fit-content"
            bg="surfaceCards.800"
            mt={{ base: 10, md: 0 }}
          >
            <Text as="h3" mb={5} color="white" fontSize="lg">
              RESUMEN DE TU PEDIDO
            </Text>
            <Flex mb={{ base: 3 }} justify="space-between">
              <Text color="surfaceCards.200">Productos (2)</Text>
              <Text color="surfaceCards.200">s/ 240.00</Text>
            </Flex>

            {/* Lista de Productos */}
            <Stack mb={{ base: 3 }} w="full" mx="auto">
              <ProductList />
              <ProductList />
            </Stack>

            <Flex mb={{ base: 3 }} justify="space-between">
              <Flex align="center">
                <Text color="surfaceCards.200" mr={2}>
                  Copas Virtuales
                </Text>
                <VirtualCup />
              </Flex>
              <Text color="surfaceCards.200">
                +20 <Icon as={CupIcon} fill="primary.500" />
              </Text>
            </Flex>

            <Flex justify="space-between">
              <Text color="surfaceCards.200">Costo de envío</Text>
              <Text color="surfaceCards.200">Por confirmar</Text>
            </Flex>

            <Flex my={5} justify="space-between">
              <Text color="white" fontSize={{ base: 'lg' }} fontWeight="500">
                TOTAL
              </Text>
              <Text color="white" fontSize={{ base: 'lg' }} fontWeight="500">
                s/ 240.00
              </Text>
            </Flex>

            <Button disabled w="full">
              FINALIZAR COMPRA
            </Button>
          </Box>
        </SimpleGrid>
      </Container>

      <Footer />
    </Box>
  )
}

export default pago
