import React from 'react'
import Head from 'next/head'

const tienda = () => {
  return (
    <>
      <Head>
        <title>Elitario || Tienda</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>TIENDA</h1>
    </>
  )
}

export default tienda
