import React from 'react'
import Head from 'next/head'

// terceros
import {
  Box,
  Flex,
  Container,
  SimpleGrid,
  Heading as HeadingC
} from '@chakra-ui/layout'
import { Icon } from '@chakra-ui/icon'
import { IconButton } from '@chakra-ui/button'
import { useDisclosure } from '@chakra-ui/hooks'

// Components
import Heading from '@/components/Heading'
import Pagination from '@/components/Pagination'
import CardProduct from '@/components/CardProduct'
import OrdenarMenu from '@/sections/Tienda/OrdenarMenu'
import FiltroModal from '@/sections/Tienda/FiltroModal'
import SliderValorados from '@/sections/Tienda/SliderValorados'

// Icons
import { FilterIcon } from '@/assets/icons'

const tienda = () => {
  const { isOpen, onOpen, onClose } = useDisclosure()

  return (
    <>
      <Head>
        <title>Elitario | Tienda</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box bg="negro.900" py={{ base: 5 }}>
        <Heading>TIENDA</Heading>
      </Box>

      <Container
        pb={10}
        bgSize="contain"
        bgRepeat="repeat"
        bgPosition="center"
        bgImage="url(/images/heroPattern.webp)"
      >
        <Flex justify="space-between" align="center" pt={{ base: 5 }}>
          <HeadingC fontWeight="500" fontSize={{ base: '2xl' }} color="white">
            Productos recientes
          </HeadingC>
          <OrdenarMenu />
        </Flex>

        <SimpleGrid templateColumns={{ base: 'minmax(0, 1fr)' }}>
          {Array(12)
            .fill(null)
            .map((_, i) => (
              <CardProduct key={i} />
            ))}
        </SimpleGrid>

        <Flex mt={5} mb={10} justify="center">
          <Pagination />
        </Flex>

        <HeadingC
          mb={5}
          fontWeight="500"
          textAlign="center"
          fontSize={{ base: '2xl' }}
          color="white"
        >
          Mejor valorados
        </HeadingC>

        <SliderValorados />
      </Container>
      {isOpen ? <FiltroModal {...{ isOpen, onClose }} /> : null}
      <IconButton
        right={5}
        bottom={5}
        pos="fixed"
        rounded="full"
        onClick={onOpen}
        colorScheme="primary"
        icon={<Icon as={FilterIcon} />}
      />
    </>
  )
}

export default tienda
